# -*- coding: utf-8 -*-
"""Python - AT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGrainesgbHtLcUsuy1T0bn28hUW2xcs
"""

#Tarefa
#Desenvolva um programa que calcule o custo de produção total de um lote e o custo por unidade de um componente eletrônico, considerando o preço e a quantidade de dois componentes básicos e um custo fixo.

#Entrada
#O programa receberá, nesta ordem, seis valores numéricos. O primeiro é um valor de ponto flutuante representando o custo unitário do componente_a. O segundo é um número inteiro indicando a quantidade de componente_a utilizada em cada produto final. O terceiro é um valor de ponto flutuante para o custo unitário do componente_b. O quarto é um número inteiro para a quantidade de componente_b utilizada por produto. O quinto é um valor de ponto flutuante que representa um custo fixo total para todo o lote de produção. Por fim, o sexto valor é um número inteiro que corresponde à quantidade total de produtos fabricados neste lote. Todos os valores serão positivos.

#Saída
#O programa deve exibir dois valores. O primeiro valor é o custo total do lote de produção, apresentado como um número de ponto flutuante. O segundo valor é o custo por unidade do produto final, também como um número de ponto flutuante, formatado para exibir exatamente duas casas decimais. Os valores devem ser apresentados um abaixo do outro.
custo_a = float(input())
qtd_a = int(input())
custo_b = float(input())
qtd_b = int(input())
custo_fixo = float(input())
qtd_produtos = int(input())

custo_variavel_unitario = (custo_a * qtd_a) + (custo_b * qtd_b)
custo_total = (custo_variavel_unitario * qtd_produtos) + custo_fixo
custo_unitario = custo_total / qtd_produtos

print(custo_total)
print(f"{custo_unitario:.2f}")

#Tarefa
#Crie um programa que capture e registre informações básicas de um paciente, consolidando-as para exibição em um formato padronizado.

#Entrada
#O programa receberá três informações distintas, fornecidas em linhas consecutivas: primeiramente, o nome completo do paciente como uma sequência de caracteres; em seguida, a idade do paciente como um número inteiro positivo; e por fim, a temperatura corporal do paciente em graus Celsius, como um número real com uma casa decimal.

#Saída
#O programa deve produzir uma única linha de saída, apresentando as informações do paciente de forma concatenada. A saída deve iniciar com a etiqueta "Nome:", seguida pelo nome completo do paciente. Posteriormente, deve apresentar "Idade:", seguido pela idade em anos. Finalmente, deve exibir "Temperatura:", seguido pela temperatura corporal, com o sufixo "°C". Para separar cada uma das informações, utilize "|", com os devidos espaços para melhorar a legibilidade.
nome = input("Digite seu nome completo: ")
idade = int(input("\nDigite sua idade: "))
temperatura = float(input("\nDigite sua temperatura corporal"))

print(f"\nNome: {nome} | Idade: {idade} | Temperatura: {temperatura:.1f}°C")

#Tarefa
#O problema consiste em calcular a soma e a média aritmética de um conjunto de valores transacionais.

#Entrada
#A entrada para o programa é constituída por uma lista contendo exclusivamente valores numéricos. Cada número representa o montante de uma transação.

#Saída
#O programa deve produzir dois valores numéricos, a soma e a média das transações.
def calcular(lista):
    soma=0
    for valor in lista:
        soma+=valor

    media=soma/len(lista)
    return soma,media

entrada=input("Digite os valores separados por espaço: ").split()
lista=[]

for x in entrada:
    lista.append(float(x))

soma,media=calcular(lista)

print(soma)
print(media)

#Tarefa
#Desenvolva uma função que receba um número inteiro não negativo e calcule o seu fatorial. Lembre-se que o fatorial de 0 é 1.

#Entrada
#Um único valor inteiro positivo ou zero.

#Saída
#A função deve exibir um valor numérico inteiro correspondente ao fatorial do número de entrada.
def fatorial(numero):
    resultado = 1
    for i in range(1, numero + 1):
        resultado *= i
    return resultado

numero = int(input())
print(fatorial(numero))

#Tarefa
#Elabore uma solução computacional que, encapsulada em uma estrutura de código, processe um valor inteiro representando uma duração em minutos, convertendo-o para um formato composto de horas e minutos. A apresentação do resultado deve ser cuidadosamente formatada para exibir singular ou plural conforme a quantidade de horas e minutos, incluindo casos onde as horas ou os minutos resultantes sejam zero. Visando melhorar a reprodutibilidade e escalabilidade deste código, a solução deve ser realizada dentro de uma função que exiba a saída solicitada abaixo.

#Entrada
#A entrada consiste em um único valor numérico inteiro, representando a duração total de um percurso em minutos. Este valor será sempre não negativo.

#Saída
#O programa deve produzir uma única linha de texto. Esta linha deve apresentar a duração convertida no formato 'X hora(s) e Y minuto(s)'. Os valores de X e Y devem corresponder, respectivamente, ao número inteiro de horas e ao número inteiro de minutos restantes após a conversão. A terminologia 'hora(s)' e 'minuto(s)' deve ser ajustada para o singular quando o valor correspondente for 1, e para o plural nos demais casos, incluindo zero. Não deve haver espaços adicionais no final da linha.
#A apresentação do resultado deve ser cuidadosamente formatada para exibir singular ou plural conforme a quantidade de horas e minutos, incluindo casos onde as horas ou os minutos resultantes sejam zero
def converte_horario(minutos_total):
    hora = minutos_total // 60
    minuto = minutos_total % 60

    if hora == 1:
        h_txt = "hora"
    else:
        h_txt = "horas"
    if minuto == 1:
        m_txt = "minuto"
    else:
        m_txt = "minutos"
    return f"{hora} {h_txt} e {minuto} {m_txt}"

valor = int(input("Digite um valor para ser convertido: "))
print(converte_horario(valor))

#Tarefa
#Desenvolva um programa que solicite ao usuário a inserção de diversos números inteiros, um por um. O programa deve continuar solicitando entradas até que o usuário digite a palavra "SAIR" (em letras maiúsculas). Após o encerramento, o programa deve processar todos os números inseridos e informar a contagem total de números pares e a contagem total de números ímpares.

#Entrada
#Uma sequência de entradas via teclado. Cada entrada pode ser um número inteiro ou a string "SAIR". Considera-se que o usuário não inserirá valores inválidos (como letras que não sejam a palavra de comando).

#Saída
#O programa deve exibir duas linhas de texto. A primeira contendo a quantidade de números pares (ex: "Pares: X") e a segunda contendo a quantidade de números ímpares (ex: "Ímpares: Y"). Caso nenhum número seja inserido antes do comando de saída, o programa deve exibir os contadores zerados.
pares=0
impares=0

while True:
    entrada=input("Digite um número inteiro ou 'SAIR' para encerrar: ")
    if entrada=="SAIR":
        break
    numero=int(entrada)
    if numero%2==0:
        pares+=1
    else:
        impares+=1

print(f"Pares: {pares}")
print(f"Ímpares: {impares}")

#Tarefa
#Desenvolva um programa que ajude Joãozinho a investigar o comportamento da função y conforme x se aproxima de 1 pelo lado esquerdo (valores menores que 1), chegando cada vez mais perto de 1. Para tentar conter esse potencial destruidor de universo, pedimos encarecidamente que coloque os cálculos dentro de uma função.

#Entrada
#Como o seu computador não tem todo o tempo do universo, você deve definir como entrada o número de passos da investigação (ex: 10 passos).

#Saída
#Uma lista de resultados que mostre para qual número a função está "convergindo" antes de chegar no 1.

#Curiosidade: Você acabou de calcular o limite dessa função quando x tende a 1.
def investigar(passos):
    resultados=[]

    for i in range(1,passos+1):
        x=1-1/(10**i)
        y=(x**2-1)/(x-1)
        resultados.append(y)

    return resultados

passos=int(input("Digite o número de passos: "))
lista=investigar(passos)

for valor in lista:
    print(valor)

#Tarefa
#Desenvolva um programa que calcule a área total da parede e a quantidade de latas de tinta necessárias. Para tal:

#Crie uma função chamada altura_parede(x) que retorne o valor de math.sin(x) + 2. (Importe o módulo math)
#Divida o comprimento de 10 metros em n fatias (retângulos).
#A largura de cada fatia será 10n.
#A área de cada fatia é altura_parede(x) * largura.
#Calcule a quantidade de tinta:
#Considere que 1 litro de tinta pinta 5 m².
#Cada lata de tinta tem 3,6 litros.
#O programa deve informar quantas latas (número inteiro) devem ser compradas. (Dica: use math.ceil() para arredondar para cima).

#Entrada
#O usuário deve inserir o número de fatias (n) para o cálculo. (Testar com 10, 100 e 1000 para ver a precisão aumentar).


#Saída
#O programa deve exibir:

#A área total aproximada da parede.
#A quantidade total de tinta necessária (em litros).
#O número mínimo de latas de 3,6L a serem compradas.
#Curiosidade: Parabéns! Você acabou de realizar uma integral.
import math

def altura_parede(x):
    return math.sin(x)+2

n = int(input("Digite o número de fatias: "))

comprimento = 10
largura = comprimento/n
area_total = 0

for i in range(n):
    x=i*largura
    area=altura_parede(x)*largura
    area_total+=area

litros= area_total / 5
latas= math.ceil(litros / 3.6)

print(f"Área total: {area_total}")
print(f"Tinta necessária (litros): {litros}")
print(f"Latas necessárias: {latas}")

#Tarefa
#Desenvolva um programa que calcule o montante final de um investimento financeiro considerando juros compostos mensais, aplicando regras condicionais de bônus ou penalidade sobre o capital. Para melhorar a qualidade deste código, é exigido que ele seja realizado majoritariamente dentro de funções.

#Entrada
#O programa receberá três valores numéricos: o capital principal inicial, a taxa de juros mensal (em formato decimal) e a duração do investimento em meses. O capital principal será um número de ponto flutuante positivo, a taxa mensal será um número de ponto flutuante positivo, e a duração em meses será um número inteiro positivo.

#Saída
#O programa deve exibir um único valor numérico, representando o montante final do investimento. O valor final deve ser truncado para apresentar apenas duas casas decimais, ignorando quaisquer dígitos adicionais. As seguintes regras devem ser aplicadas sequencialmente para o cálculo:

#Regra de Penalidade: Se a duração total do investimento for estritamente inferior a 3 meses, o capital não renderá juros. Em vez disso, uma penalidade fixa de 2% do capital principal inicial será deduzida. O valor final será o capital principal inicial menos essa penalidade.
#Regra de Bônus: Se a duração total do investimento for igual ou superior a 18 meses, um bônus adicional equivalente a 0.5% do capital principal inicial é somado ao capital principal antes da aplicação dos juros compostos. Esta regra é prioritária e não afeta a aplicação da Regra de Penalidade, pois as condições de duração são mutuamente exclusivas.
#Para durações que não se enquadram nas regras 2 ou 3 (ou seja, 3 meses <= duração < 18 meses), ou após a aplicação do bônus (se aplicável), o montante final é calculado aplicando a taxa mensal ao capital a cada mês sucessivo, pelo número total de meses de investimento.
#Regra de Juros Compostos

#A fórmula dos juros compostos é:
#M=C⋅(1+i)t

#Onde:
#M = Montante (valor final)
#C = Capital inicial (valor investido)
#i = Taxa de juros (em decimal)
#t = Tempo (número de períodos)

#Observação:
#A taxa i deve estar em formato decimal e ter como base o mesmo período do tempo. Exemplo:
#5% = 0,05
#10% = 0,10

import math

def aplicar_penalidade(capital):
    return capital - (capital * 0.02)

def aplicar_bonus(capital):
    return capital + (capital * 0.005)

def juros_compostos(capital,taxa,tempo):
    return capital * ((1 + taxa)**tempo)

def truncar(valor):
    return int(valor * 100) / 100

def calcular_montante(capital,taxa,meses):
    if meses < 3:
        return aplicar_penalidade(capital)

    if meses >= 18:
        capital = aplicar_bonus(capital)

    return juros_compostos(capital,taxa,meses)

capital = float(input("Capital inicial: "))
taxa = float(input("Taxa mensal (decimal): "))
meses = int(input("Meses: "))

resultado = calcular_montante(capital,taxa,meses)
resultado = truncar(resultado)

print(resultado)

#Tarefa
#Escreva uma função que, recebe duas listas do usuário e retorna uma nova chamada lista_intersecao contendo apenas os elementos que estão presentes em ambas as listas. Para melhorar a replicabilidade do código, é necessário que a análise das interseções seja realizada dentro de uma função.

#Entrada
#A função receberá duas listas. A primeira representa os códigos dos produtos no Armazém A e a segunda os códigos no Armazém B.

#Saída
#O programa deve exibir a lista lista_intersecao contendo os elementos comuns.
def lista_intersecao(lista1,lista2):
    resultado=[]

    for item in lista1:
        if item in lista2 and item not in resultado:
            resultado.append(item)
    return resultado

lista1=list(map(int,input("Lista A: ").split()))
lista2=list(map(int,input("Lista B: ").split()))
res=lista_intersecao(lista1,lista2)

print(res)

#Tarefa
#Desenvolva um programa que estime o valor de pi utilizando o método de Monte Carlo.

#A Lógica do Experimento:
#Imagine um círculo de raio r=1
#inscrito em um quadrado de lado 2.
#A área do círculo é π⋅r2=π
#A área do quadrado é 22=4
#A razão entre as áreas é π4

#Se gerarmos muitos pontos aleatórios (x, y) dentro do quadrado, a proporção de pontos que caem dentro do círculo em relação ao total de pontos será aproximadamente π4
#Portanto: π≈4⋅(pontos dentro do círculototal de pontos)
#Obs.: Para gerar os pontos aleatórios, utilize a função random.random() da biblioteca random. Essa função gera um número decimal entre 0 e 1.

#Entrada
#Um número inteiro positivo representando o número total de pontos (tentativas) a serem sorteados. (Dica: Use valores altos como 100000 para uma melhor precisão.)

#Saída
#O programa deve exibir o valor estimado de Pi para 10, 100, 1000, 10000 e 100000 pontos.
import random

def estimar_pi(n):
    dentro = 0

    for i in range(n):
        x = random.random()
        y = random.random()
        if x * x + y * y <= 1:
            dentro += 1
    return 4 * (dentro / n)

valores = [10,100,1000,10000,100000]

for v in valores:
    pi = estimar_pi(v)
    print(pi)

#Tarefa
#Crie um programa que compare duas listas de strings, onde cada lista representa as respostas de um aluno (ex: 'A', 'B', 'C'). O programa deve verificar, posição por posição, em quais questões os alunos deram a mesma resposta e, ao final, informar quem teve o maior número de acertos baseando-se em um gabarito fornecido.

#Entrada
#Três listas de caracteres: a primeira é o gabarito_oficial, a segunda é respostas_aluno_1 e a terceira é respostas_aluno_2. Todas as listas possuem o mesmo tamanho.

#Saída
#O programa deve exibir o número de acertos de cada aluno e uma mensagem indicando qual aluno venceu (ex: "Aluno 1 venceu", "Aluno 2 venceu" ou "Empate").
def corrigir(gabarito,respostas):
    acertos=0

    for i in range(len(gabarito)):
        if respostas[i]==gabarito[i]:
            acertos+=1
    return acertos

gabarito=input("Gabarito: ").split()
aluno1=input("Respostas aluno 1: ").split()
aluno2=input("Respostas aluno 2: ").split()

acertos1=corrigir(gabarito,aluno1)
acertos2=corrigir(gabarito,aluno2)

print(acertos1)
print(acertos2)

if acertos1>acertos2:
    print("Aluno 1 venceu")
elif acertos2>acertos1:
    print("Aluno 2 venceu")
else:
    print("Empate")

#Tarefa
#Desenvolva uma função que receba uma string contendo um CPF no formato XXX.XXX.XXX-XX e verifique se o CPF é válido.

#Entrada
#Uma string composta por 11 caracteres numéricos.

#Saída
#O programa deve exibir a mensagem "CPF Válido" se os dígitos verificadores estiverem corretos, ou "CPF Inválido" caso contrário.

#Regras Resumidas para Validação de CPF:
#O CPF deve conter exatamente 11 dígitos numéricos.
#Não pode ser uma sequência de números iguais (ex: 11111111111, 22222222222).
#Os 9 primeiros dígitos formam a base do CPF.
#O 10º dígito é o primeiro dígito verificador, calculado com pesos de 10 a 2.
#O 11º dígito é o segundo dígito verificador, calculado com pesos de 11 a 2.
#Para cada dígito verificador:
#Multiplicar os números anteriores pelos pesos.
#Somar os resultados.
#Calcular o resto da divisão por 11.
#O dígito verificador é 11 - o resto calculado acima.
#Se o resultado for 10 ou 11, considerar 0. - Atenção: para o primeiro dígito verificador são utilizados os 9 dígitos base, para o segundo dígito verificador são utilizados os 9 dígitos base E o primeiro dígito verificador
#O CPF é válido se os dois dígitos calculados forem iguais aos informados.
def validar_cpf(cpf):
    cpf=cpf.replace(".","").replace("-","")

    if len(cpf)!=11:
        return False
    if cpf==cpf[0]*11:
        return False
    soma=0
    peso=10

    for i in range(9):
        soma+=int(cpf[i])*peso
        peso-=1
    resto=soma%11
    dig1=11-resto

    if dig1>=10:
        dig1=0
    soma=0
    peso=11

    for i in range(10):
        soma+=int(cpf[i])*peso
        peso-=1
    resto=soma%11
    dig2=11-resto

    if dig2>=10:
        dig2=0
    if dig1==int(cpf[9]) and dig2==int(cpf[10]):
        return True
    return False

cpf=input("Digite o CPF: ")

if validar_cpf(cpf):
    print("CPF Válido")
else:
    print("CPF Inválido")

#Tarefa
#Elabore um programa que gerencie uma campanha de arrecadação, somando doações individuais até que uma meta predefinida seja alcançada ou superada. O programa deve monitorar o progresso e apresentar o resultado final com base no cenário alcançado.

#Entrada
#A entrada consiste em uma sequência de informações. A primeira informação é um número inteiro que representa o valor da meta de arrecadação a ser alcançada. As informações subsequentes são uma série de números reais, cada um correspondendo a uma doação individual recebida. Estes valores serão fornecidos um por um, e o programa deve continuar processando as doações até que a soma total acumulada seja igual ou superior à meta estabelecida. Todos os valores de doação serão positivos e devem ser considerados válidos.

#Saída
#O programa deve produzir uma única linha de texto. Esta linha deve apresentar o valor total arrecadado, formatado com duas casas decimais. Após o valor, deve haver uma mensagem específica. Se o total arrecadado for exatamente igual à meta, a mensagem deve indicar que a meta foi atingida. Se o total arrecadado for superior à meta, a mensagem deve informar que a meta foi superada, detalhando também o valor exato pelo qual a meta foi excedida, formatado com duas casas decimais.
meta = int(input("Meta: "))
total = 0

while total < meta:
    doacao = float(input("Doação: "))
    total += doacao

if total == meta:
    print(f"{total:.2f} Meta atingida")
else:
    excesso = total - meta
    print(f"{total:.2f} Meta superada em {excesso:.2f}")

#Tarefa
#Desenvolva um programa que gerencie a posição de um personagem em um grid de 20 x 20 (coordenadas de 0 a 19). O programa deve rodar em um loop contínuo, aceitando comandos de direção até que o objetivo seja alcançado.

#Requisitos Técnicos:
#Configuração de Variáveis:
#O personagem começa na posição: X = 3 e Y = 2.
#A bandeira (objetivo) está na posição: X = 15 e Y = 18.

#Movimentação e Comandos:
#O programa deve ler a entrada do usuário:
#w: Sobe (diminui Y)
#s: Desce (aumenta Y)
#a: Esquerda (diminui X)
#d: Direita (aumenta X)
#Garanta que o comando funcione com letras maiúsculas ou minúsculas.

#Processamento por Funções:
#Crie uma função que receba a posição atual e o comando, retornando a nova posição após validar se o movimento é possível.

#Renderização do Grid:
#Antes do primeiro comando, e após cada comando, o programa deve imprimir o grid de 20 linhas por 20 colunas.

#Use os seguintes caracteres:
#. (ponto) para espaços vazios.
#P (letra P) para a posição atual do Personagem.
#B (letra B) para a posição da Bandeira.

#Regras de Fronteira:
#O grid possui limites entre 0 e 19. O personagem não pode sair desses limites. Se o usuário tentar ir para X=-1 ou Y=20, por exemplo, o programa deve exibir uma mensagem de "Colisão com a fronteira!" e manter o personagem no mesmo lugar.

#Ciclo do Jogo:
#O jogo deve continuar até que o personagem chegue na mesma posição da bandeira.

#Saída de Dados:
#Ao chegar no objetivo, exiba: "Objetivo alcançado! Missão cumprida.". Caso o input do usuário seja "sair", o jogo é encerrado.
def mover_personagem(x,y,comando):
    comando=comando.lower()

    novo_x=x
    novo_y=y

    if comando == "w":
        novo_y -= 1
    elif comando == "s":
        novo_y += 1
    elif comando == "a":
        novo_x -= 1
    elif comando == "d":
        novo_x += 1

    if novo_x < 0 or novo_x > 19 or novo_y < 0 or novo_y > 19:
        print("Colisão com a fronteira!")
        return x,y

    return novo_x,novo_y

def desenhar_grid(x,y,flag_x,flag_y):
    for linha in range(20):
        texto = ""
        for coluna in range(20):
            if coluna == x and linha == y:
                texto+="P"  #personagem
            elif coluna == flag_x and linha == flag_y:
                texto += "B"  #bandeira
            else:
                texto += "."
        print(texto)

x = 3
y = 2

flag_x = 15
flag_y = 18

desenhar_grid(x,y,flag_x,flag_y)

while True:
    comando = input("Digite (w,a,s,d) ou sair: ")

    if comando.lower() == "sair":
        break

    x,y = mover_personagem(x,y,comando)

    desenhar_grid(x,y,flag_x,flag_y)

    if x == flag_x and y == flag_y:
        print("Objetivo alcançado! Missão cumprida.")
        break